default: &default
  port: ":8080"
  mysql:
    host: "localhost"
    user: root
    password: "1"
    database: sequencing
    network: tcp
    port: "3306"
  redis:
    network: tcp
    address: "127.0.0.1:6379"
    password: ""
  session:
    size: 24
    key: sequencing-sec-key
    name: sequencing-session
  consts:
    boardType: ['sample', 'reaction', 'primer']
    primerStoreType: ['90days', '1year', 'infinate']
    primerStatus: ['not_receive', 'ok', 'lack', 'runout']
    primerNewStatus: ['not_receive', 'ok']
    spliceStatus: ['new', 'run', 'finish', 'concession']
    diluteThickNess: '5pmol/ul'
    dilutePrimerStatus: ['ok', 'lack', 'runout']
    orderStatus: ['new', 'run', 'to_checkout', 'checkout', 'finish']
    boardStatus: ['new', 'run', 'finish']
    transportCondition: ['4-10degree', 'dry_ice', 'room_temperature']
    abiInstruments: ['1','2','3','4']
    interpreteResult: ['pass', 'concession', 'rework', 'reshake']
    interpreteStatus: ['interpreting', 'interpreted', 'sent']
    billStatus: ['sign_bill', 'invoice', 'confirm_detail', 'payed', 'bad_debt']
    payType: ['check', 'cash', 'transfer_accounts']
    emailType: ['primer_expire', 'precheck', 'interprete']
  reaction_file:
    path: '/home/wangfan/golang/src/sequencing/reaction_files'
    suffix: ['.ab1', '.seq']
development:
  <<: *default
test:
  <<: *default
  port: ":8079"
  mysql:
    host: "localhost"
    user: root
    password: "1"
    database: sequencing_test
    network: tcp
    port: "3306"
