# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard :shell do
  watch(%r{.+\.go$}) do |f|
    r = `GOENV=test ginkgo -failFast`
    #a = `echo $PATH`
    puts r
    #puts "#{f} changed"
  end
end
